apiVersion: v1
kind: Pod
metadata:
  namespace: my-ns
  name: app
spec:
  containers:
    - name: c01
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-c01111111; sleep 2; done"]
    - name: c02
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello-c02222222; sleep 2; done"]