---
# tasks file for basic

- name: Set timezone
  timezone:
    name: Etc/UTC

- name: Set hostname
  command: hostnamectl set-hostname {{ inventory_hostname }}

- name: Add hostname to "{{ etc_hosts_path }}"
  lineinfile:
    path: "{{ etc_hosts_path }}"
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ inventory_hostname }}'
    owner: root
    group: root
    mode: 0644

- name: Add hostname to "{{ etc_hosts_path }}"
  lineinfile:
    path: "{{ etc_hosts_path }}"
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ inventory_hostname }}'
    owner: root
    group: root
    mode: 0644

- name: apt update and Preinstall Tools
  apt:
    name:
      - net-tools
    state: present
    update_cache: yes

- name: Install deb Package
  apt:
    deb:
      - https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb
      - /home/mohsen/zabbix-release_latest+ubuntu24.04_all.deb

